#Figure S2

Data_rep <- read_excel("Data_LMRenamed.xlsx")

repeated_data_prep = Data_rep %>% group_by(Genus, Season_ID) %>%
		mutate(wing_n = n())

repeated_data =  subset(repeated_data_prep, wing_n > 4)

repeatability = repeated_data %>% group_by(Genus, Season_ID, WingSide, WingID) %>% 
	mutate(mean_X.1 = mean(X.1),
				mean_Y.1 = mean(Y.1),
				mean_X.2 = mean(X.2),
				mean_Y.2 = mean(Y.2),
				mean_X.3 = mean(X.3),
				mean_Y.3 = mean(Y.3),
				mean_X.4 = mean(X.4),
				mean_Y.4 = mean(Y.4),
				mean_X.5 = mean(X.5),
				mean_Y.5 = mean(Y.5),
				mean_X.6 = mean(X.6),
				mean_Y.6 = mean(Y.6),
				mean_X.7 = mean(X.7),
				mean_Y.7 = mean(Y.7),
				mean_X.8 = mean(X.8),
				mean_Y.8 = mean(Y.8),
				mean_X.9 = mean(X.9),
				mean_Y.9 = mean(Y.9),
				mean_X.10 = mean(X.10),
				mean_Y.10 = mean(Y.10),
				mean_X.11 = mean(X.11),
				mean_Y.11 = mean(Y.11),
				mean_X.12 = mean(X.12),
				mean_Y.12 = mean(Y.12),
				mean_X.13 = mean(X.13),
				mean_Y.13 = mean(Y.13),
				mean_X.14 = mean(X.14),
				mean_Y.14 = mean(Y.14),
				mean_X.15 = mean(X.15),
				mean_Y.15 = mean(Y.15),
				mean_X.16 = mean(X.16),
				mean_Y.16 = mean(Y.16),
				mean_X.17 = mean(X.17),
				mean_Y.17 = mean(Y.17),
				mean_dif_X.1 = abs(mean_X.1 - X.1),
				mean_dif_Y.1 = abs(mean_Y.1 - Y.1),
				mean_dif_X.2 = abs(mean_X.2 - X.2),
				mean_dif_Y.2 = abs(mean_Y.2 - Y.2),
				mean_dif_X.3 = abs(mean_X.3 - X.3),
				mean_dif_Y.3 = abs(mean_Y.3 - Y.3),
				mean_dif_X.4 = abs(mean_X.4 - X.4),
				mean_dif_Y.4 = abs(mean_Y.4 - Y.4),
				mean_dif_X.5 = abs(mean_X.5 - X.5),
				mean_dif_Y.5 = abs(mean_Y.5 - Y.5),
				mean_dif_X.6 = abs(mean_X.6 - X.6),
				mean_dif_Y.6 = abs(mean_Y.6 - Y.6),
				mean_dif_X.7 = abs(mean_X.7 - X.7),
				mean_dif_Y.7 = abs(mean_Y.7 - Y.7),
				mean_dif_X.8 = abs(mean_X.8 - X.8),
				mean_dif_Y.8 = abs(mean_Y.8 - Y.8),
				mean_dif_X.9 = abs(mean_X.9 - X.9),
				mean_dif_Y.9 = abs(mean_Y.9 - Y.9),
				mean_dif_X.10 = abs(mean_X.10 - X.10),
				mean_dif_Y.10 = abs(mean_Y.10 - Y.10),
				mean_dif_X.11 = abs(mean_X.11 - X.11),
				mean_dif_Y.11 = abs(mean_Y.11 - Y.11),
				mean_dif_X.12 = abs(mean_X.12 - X.12),
				mean_dif_Y.12 = abs(mean_Y.12 - Y.12),
				mean_dif_X.13 = abs(mean_X.13 - X.13),
				mean_dif_Y.13 = abs(mean_Y.13 - Y.13),
				mean_dif_X.14 = abs(mean_X.14 - X.14),
				mean_dif_Y.14 = abs(mean_Y.14 - Y.14),
				mean_dif_X.15 = abs(mean_X.15 - X.15),
				mean_dif_Y.15 = abs(mean_Y.15 - Y.15),
				mean_dif_X.16 = abs(mean_X.16 - X.16),
				mean_dif_Y.16 = abs(mean_Y.16 - Y.16),
				mean_dif_X.17 = abs(mean_X.17 - X.17),
				mean_dif_Y.17 = abs(mean_Y.17 - Y.17),
				repeatability_X.1 = mean_dif_X.1/ abs(mean_X.1),
				repeatability_Y.1 = mean_dif_Y.1/ abs(mean_Y.1),
				repeatability_X.2 = mean_dif_X.2/ abs(mean_X.2),
				repeatability_Y.2 = mean_dif_Y.2/ abs(mean_Y.2),
				repeatability_X.3 = mean_dif_X.3/ abs(mean_X.3),
				repeatability_Y.3 = mean_dif_Y.3/ abs(mean_Y.3),
				repeatability_X.4 = mean_dif_X.4/ abs(mean_X.4),
				repeatability_Y.4 = mean_dif_Y.4/ abs(mean_Y.4),
				repeatability_X.5 = mean_dif_X.5/ abs(mean_X.5),
				repeatability_Y.5 = mean_dif_Y.5/ abs(mean_Y.5),
				repeatability_X.6 = mean_dif_X.6/ abs(mean_X.6),
				repeatability_Y.6 = mean_dif_Y.6/ abs(mean_Y.6),
				repeatability_X.7 = mean_dif_X.7/ abs(mean_X.7),
				repeatability_Y.7 = mean_dif_Y.7/ abs(mean_Y.7),
				repeatability_X.8 = mean_dif_X.8/ abs(mean_X.8),
				repeatability_Y.8 = mean_dif_Y.8/ abs(mean_Y.8),
				repeatability_X.9 = mean_dif_X.9/ abs(mean_X.9),
				repeatability_Y.9 = mean_dif_Y.9/ abs(mean_Y.9),
				repeatability_X.10 = mean_dif_X.10/ abs(mean_X.10),
				repeatability_Y.10 = mean_dif_Y.10/ abs(mean_Y.10),
				repeatability_X.11 = mean_dif_X.11/ abs(mean_X.11),
				repeatability_Y.11 = mean_dif_Y.11/ abs(mean_Y.11),
				repeatability_X.12 = mean_dif_X.12/ abs(mean_X.12),
				repeatability_Y.12 = mean_dif_Y.12/ abs(mean_Y.12),
				repeatability_X.13 = mean_dif_X.13/ abs(mean_X.13),
				repeatability_Y.13 = mean_dif_Y.13/ abs(mean_Y.13),
				repeatability_X.14 = mean_dif_X.14/ abs(mean_X.14),
				repeatability_Y.14 = mean_dif_Y.14/ abs(mean_Y.14),
				repeatability_X.15 = mean_dif_X.15/ abs(mean_X.15),
				repeatability_Y.15 = mean_dif_Y.15/ abs(mean_Y.15),
				repeatability_X.16 = mean_dif_X.16/ abs(mean_X.16),
				repeatability_Y.16 = mean_dif_Y.16/ abs(mean_Y.16),
				repeatability_X.17 = mean_dif_X.17/ abs(mean_X.17),
				repeatability_Y.17 = mean_dif_Y.17/ abs(mean_Y.17))

repeatability_summary = subset(repeatability [,c(1, 128:161)])

names(repeatability_summary) <- c(	"Season_ID", 
															"repeatability_X1", 
															"repeatability_Y1", 
															"repeatability_X2", 
															"repeatability_Y2", 
															"repeatability_X3", 
															"repeatability_Y3", 
															"repeatability_X4", 
															"repeatability_Y4", 
															"repeatability_X5", 
															"repeatability_Y5", 
															"repeatability_X6", 
															"repeatability_Y6", 
															"repeatability_X7", 
															"repeatability_Y7", 
															"repeatability_X8", 
															"repeatability_Y8", 
															"repeatability_X9", 
															"repeatability_Y9", 
															"repeatability_X10", 
															"repeatability_Y10", 
															"repeatability_X11", 
															"repeatability_Y11", 
															"repeatability_X12", 
															"repeatability_Y12", 
															"repeatability_X13", 
															"repeatability_Y13", 
															"repeatability_X14", 
															"repeatability_Y14", 
															"repeatability_X15", 
															"repeatability_Y15", 
															"repeatability_X16", 
															"repeatability_Y16", 
															"repeatability_X17", 
															"repeatability_Y17")

repeatability_summary_gathered = gather(repeatability_summary, key = "Season_ID", value = "repeatability")%>%
	mutate(Season_ID = factor(Season_ID, levels = c(
															"repeatability_X1", 
															"repeatability_Y1", 
															"repeatability_X2", 
															"repeatability_Y2", 
															"repeatability_X3", 
															"repeatability_Y3", 
															"repeatability_X4", 
															"repeatability_Y4", 
															"repeatability_X5", 
															"repeatability_Y5", 
															"repeatability_X6", 
															"repeatability_Y6", 
															"repeatability_X7", 
															"repeatability_Y7", 
															"repeatability_X8", 
															"repeatability_Y8", 
															"repeatability_X9", 
															"repeatability_Y9", 
															"repeatability_X10", 
															"repeatability_Y10", 
															"repeatability_X11", 
															"repeatability_Y11", 
															"repeatability_X12", 
															"repeatability_Y12", 
															"repeatability_X13", 
															"repeatability_Y13", 
															"repeatability_X14", 
															"repeatability_Y14", 
															"repeatability_X15", 
															"repeatability_Y15", 
															"repeatability_X16", 
															"repeatability_Y16", 
															"repeatability_X17", 
															"repeatability_Y17")))

ggplot(data = repeatability_summary_gathered, aes( x = Season_ID, y = repeatability*100 ))+
	geom_boxplot(size = .2, outlier.size = .1, outlier.shape = NA) +
	geom_jitter(size = .1, alpha = .1, width = .1)+
	theme_classic()+
	#ylim(0, 2) +
	xlab("") + ylab("measurement error (% of centroid size)")+
	theme(	axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
			legend.position = "none")

range(repeatability_summary_gathered$repeatability*100)
mean(repeatability_summary_gathered$repeatability*100)
sqrt(var(repeatability_summary_gathered$repeatability*100)/length(repeatability_summary_gathered$repeatability))

ggsave('Fig. repeatability.pdf',h = 100, w = 140, units = 'mm', scale = 1)